/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JFormattedTextField;
import javax.swing.JTable;

/**
 *
 * @author bryan
 */
public class guiCountry extends javax.swing.JFrame {

    /**
     * Creates new form guiCountry
     */
    public guiCountry() {
        initComponents();
        actualizarTabla("SELECT * FROM Country;");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        caja1 = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        caja2 = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        combo1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        caja3 = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        caja4 = new javax.swing.JFormattedTextField();
        caja5 = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        caja6 = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        caja7 = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        caja8 = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        caja9 = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        caja10 = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        caja11 = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        caja12 = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        caja13 = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        caja14 = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();

        setTitle("Formulario país");
        setMinimumSize(new java.awt.Dimension(881, 527));
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Código");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 50, 14);

        try {
            caja1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UUU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        caja1.setToolTipText("Introduce el código del país");
        caja1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja1ActionPerformed(evt);
            }
        });
        getContentPane().add(caja1);
        caja1.setBounds(60, 10, 50, 25);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 40, 80, 14);

        caja2.setToolTipText("Introduce el nombre de la ciudad");
        caja2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja2ActionPerformed(evt);
            }
        });
        caja2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                caja2KeyPressed(evt);
            }
        });
        getContentPane().add(caja2);
        caja2.setBounds(110, 40, 170, 25);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Continente");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(480, 10, 80, 14);

        combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asia", "Europe", "North America", "Africa", "Oceania", "Antarctica", "South America" }));
        combo1.setSelectedIndex(-1);
        combo1.setToolTipText("Selecciona el continente");
        getContentPane().add(combo1);
        combo1.setBounds(600, 10, 150, 25);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Región");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(480, 40, 80, 14);

        try {
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        caja3.setToolTipText("Introduce la región en la que se encuentra el país");
        caja3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja3ActionPerformed(evt);
            }
        });
        caja3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                caja3KeyPressed(evt);
            }
        });
        getContentPane().add(caja3);
        caja3.setBounds(600, 40, 101, 25);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Área de la superficie");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(480, 70, 120, 14);

        caja4.setToolTipText("Introduce el área de la superficie");
        caja4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja4ActionPerformed(evt);
            }
        });
        caja4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                caja4KeyPressed(evt);
            }
        });
        getContentPane().add(caja4);
        caja4.setBounds(600, 70, 101, 25);

        try {
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        caja5.setToolTipText("Introduce el año de independencia");
        caja5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja5ActionPerformed(evt);
            }
        });
        caja5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                caja5KeyPressed(evt);
            }
        });
        getContentPane().add(caja5);
        caja5.setBounds(570, 240, 60, 25);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Año de independencia");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(420, 240, 150, 14);

        try {
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        caja6.setToolTipText("Introduce la cantidad de la población");
        caja6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja6ActionPerformed(evt);
            }
        });
        caja6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                caja6KeyPressed(evt);
            }
        });
        getContentPane().add(caja6);
        caja6.setBounds(230, 170, 130, 25);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Población");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 170, 100, 14);

        caja7.setToolTipText("Introduce la esperanza de vida de los habitantes");
        caja7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja7ActionPerformed(evt);
            }
        });
        caja7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                caja7KeyPressed(evt);
            }
        });
        getContentPane().add(caja7);
        caja7.setBounds(230, 200, 60, 25);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Produco nacional bruto");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 230, 170, 14);

        try {
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        caja8.setToolTipText("Introduce el producto anual bruto");
        caja8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja8ActionPerformed(evt);
            }
        });
        caja8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                caja8KeyPressed(evt);
            }
        });
        getContentPane().add(caja8);
        caja8.setBounds(230, 230, 130, 25);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Antiguo produco nacional bruto");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 260, 220, 14);

        try {
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        caja9.setToolTipText("Introduce el producto bruto anual anterior");
        caja9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja9ActionPerformed(evt);
            }
        });
        caja9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                caja9KeyPressed(evt);
            }
        });
        getContentPane().add(caja9);
        caja9.setBounds(230, 260, 130, 25);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nombre local");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 70, 100, 14);

        try {
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        caja10.setToolTipText("Introduce el nombre local");
        caja10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja10ActionPerformed(evt);
            }
        });
        caja10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                caja10KeyPressed(evt);
            }
        });
        getContentPane().add(caja10);
        caja10.setBounds(110, 70, 170, 25);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Forma de gobierno");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(420, 150, 140, 14);

        try {
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        caja11.setToolTipText("Introduce la forma de gobierno");
        caja11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja11ActionPerformed(evt);
            }
        });
        caja11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                caja11KeyPressed(evt);
            }
        });
        getContentPane().add(caja11);
        caja11.setBounds(570, 150, 200, 25);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Cabeza de estado");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(420, 180, 150, 14);

        caja12.setToolTipText("Introduce el nombre de la cabeza de estado");
        caja12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja12ActionPerformed(evt);
            }
        });
        caja12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                caja12KeyPressed(evt);
            }
        });
        getContentPane().add(caja12);
        caja12.setBounds(570, 180, 240, 25);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Capital");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(420, 210, 150, 14);

        try {
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        caja13.setToolTipText("Introduce el nombre de la capìtal");
        caja13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja13ActionPerformed(evt);
            }
        });
        caja13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                caja13KeyPressed(evt);
            }
        });
        getContentPane().add(caja13);
        caja13.setBounds(570, 210, 170, 25);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Código secundario");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(120, 10, 110, 14);

        try {
            caja14.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        caja14.setToolTipText("Introduce el código secundario");
        caja14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja14ActionPerformed(evt);
            }
        });
        getContentPane().add(caja14);
        caja14.setBounds(230, 10, 50, 25);

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Esperanza de vida");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(10, 200, 160, 14);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar);
        btnLimpiar.setBounds(750, 260, 100, 23);

        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 300, 840, 120);

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\bryan\\OneDrive\\one drive\\Documentos\\NetBeansProjects\\ProyectoFinalTBD\\archivos\\guiCountry.png")); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(0, 0, 1090, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void actualizarTabla(String sql) {
		ResultSetTableModel modeloDatos =null;
		try {
			modeloDatos = new ResultSetTableModel("com.mysql.cj.jdbc.Driver","jdbc:mysql://localhost:3306/world",sql);
		} catch (ClassNotFoundException e1) {
			e1.printStackTrace();
		} catch (SQLException e1) {
			e1.printStackTrace();
		}
                jScrollPane1.getViewport().remove(jTable1);
		jTable1 = new JTable(modeloDatos);
		jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
		    @Override
		    public void mouseClicked(java.awt.event.MouseEvent evt) {
		    	obtenerRegistroTabla();
		    }
		});
                jScrollPane1.getViewport().add(jTable1);
                
	}
    
    public void obtenerRegistroTabla(){
        caja1.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),0));
        caja2.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),1));
        combo1.setSelectedItem(""+jTable1.getValueAt(jTable1.getSelectedRow(),2));
        caja3.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),3));
        caja4.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),4));
        caja5.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),5));
        caja6.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),6));
        caja7.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),7));
        caja8.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),8));
        caja9.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),9));
        caja10.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),10));
        caja11.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),11));
        caja12.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),12));
        caja13.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),13));
        caja14.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),14));
    }
    
    private void caja1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja1ActionPerformed

    private void caja2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja2ActionPerformed

    private void caja3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja3ActionPerformed

    private void caja4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja4ActionPerformed

    private void caja5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja5ActionPerformed

    private void caja6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja6ActionPerformed

    private void caja7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja7ActionPerformed

    private void caja8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja8ActionPerformed

    private void caja9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja9ActionPerformed

    private void caja10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja10ActionPerformed

    private void caja11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja11ActionPerformed

    private void caja12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja12ActionPerformed

    private void caja13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja13ActionPerformed

    private void caja14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja14ActionPerformed

    private void caja2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja2KeyPressed
        int code = evt.getKeyCode();
        int limite = 52;
        if ((caja2.getText().equals("")?true:!(caja2.getText().charAt(caja2.getText().length()-1)==' '&&code==KeyEvent.VK_SPACE))&&(caja2.getText().length()<limite||code==KeyEvent.VK_BACK_SPACE)) {
                caja2.setEditable(true);
        }else{
                caja2.setEditable(false);
        }
    }//GEN-LAST:event_caja2KeyPressed

    private void caja3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja3KeyPressed
        int code = evt.getKeyCode();
        int limite = 26;
        if ((caja3.getText().equals("")?true:!(caja3.getText().charAt(caja3.getText().length()-1)==' '&&code==KeyEvent.VK_SPACE))&&(caja3.getText().length()<limite||code==KeyEvent.VK_BACK_SPACE)) {
                caja3.setEditable(true);
        }else{
                caja3.setEditable(false);
        }
    }//GEN-LAST:event_caja3KeyPressed
    int peCaja4 = 0;
    private void caja4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja4KeyPressed
        int code=evt.getKeyCode();
        int limite1 = 10;
        int limite2 = 2;
        JFormattedTextField caja = caja4;
	if (((evt.getKeyChar() >= '0'&&evt.getKeyChar() <= '9')&&!caja.getText().contains("."))&&caja.getText().length()<(limite1)||(code==KeyEvent.VK_BACK_SPACE)) {
            caja.setEditable(true);
        }else if((caja.getText().length()<(limite1+1))&&(evt.getKeyChar() == '.'&&!caja.getText().contains("."))){
            peCaja4 = caja.getText().length();
            caja.setEditable(true);
	}else if((evt.getKeyChar() >= '0'&&evt.getKeyChar() <= '9')&&(caja.getText().length()<(peCaja4+limite2+1))&&caja.getText().contains(".")){
            caja.setEditable(true);
        }else{
            caja.setEditable(false);
	}
    }//GEN-LAST:event_caja4KeyPressed

    private void caja5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja5KeyPressed
        int code=evt.getKeyCode();
	int limite=4;
        JFormattedTextField caja = caja5;
	if (((evt.getKeyChar() >= '0'&&evt.getKeyChar() <= '9'))&&caja.getText().length()<limite||(code==KeyEvent.VK_BACK_SPACE)) {
		caja.setEditable(true);
	}else{
		caja.setEditable(false);
	}
    }//GEN-LAST:event_caja5KeyPressed

    private void caja6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja6KeyPressed
        int code=evt.getKeyCode();
	int limite=10;
        JFormattedTextField caja = caja6;
	if (((evt.getKeyChar() >= '0'&&evt.getKeyChar() <= '9'))&&caja.getText().length()<limite||(code==KeyEvent.VK_BACK_SPACE)) {
		caja.setEditable(true);
	}else{
		caja.setEditable(false);
	}
    }//GEN-LAST:event_caja6KeyPressed

    int peCaja7 = 0;
    private void caja7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja7KeyPressed
        int code=evt.getKeyCode();
        int limite1 = 3;
        int limite2 = 1;
        JFormattedTextField caja = caja7;
	if (((evt.getKeyChar() >= '0'&&evt.getKeyChar() <= '9')&&!caja.getText().contains("."))&&caja.getText().length()<(limite1)||(code==KeyEvent.VK_BACK_SPACE)) {
            caja.setEditable(true);
        }else if((caja.getText().length()<(limite1+1))&&(evt.getKeyChar() == '.'&&!caja.getText().contains("."))){
            peCaja7 = caja.getText().length();
            caja.setEditable(true);
	}else if((evt.getKeyChar() >= '0'&&evt.getKeyChar() <= '9')&&(caja.getText().length()<(peCaja7+limite2+1))&&caja.getText().contains(".")){
            caja.setEditable(true);
        }else{
            caja.setEditable(false);
	}
    }//GEN-LAST:event_caja7KeyPressed

    int peCaja8 = 0;
    private void caja8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja8KeyPressed
        int code=evt.getKeyCode();
        int limite1 = 10;
        int limite2 = 2;
        JFormattedTextField caja = caja8;
	if (((evt.getKeyChar() >= '0'&&evt.getKeyChar() <= '9')&&!caja.getText().contains("."))&&caja.getText().length()<(limite1)||(code==KeyEvent.VK_BACK_SPACE)) {
            caja.setEditable(true);
        }else if((caja.getText().length()<(limite1+1))&&(evt.getKeyChar() == '.'&&!caja.getText().contains("."))){
            peCaja8 = caja.getText().length();
            caja.setEditable(true);
	}else if((evt.getKeyChar() >= '0'&&evt.getKeyChar() <= '9')&&(caja.getText().length()<(peCaja8+limite2+1))&&caja.getText().contains(".")){
            caja.setEditable(true);
        }else{
            caja.setEditable(false);
	}
    }//GEN-LAST:event_caja8KeyPressed

    int peCaja9 = 0;
    private void caja9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja9KeyPressed
        int code=evt.getKeyCode();
        int limite1 = 10;
        int limite2 = 2;
        JFormattedTextField caja = caja9;
	if (((evt.getKeyChar() >= '0'&&evt.getKeyChar() <= '9')&&!caja.getText().contains("."))&&caja.getText().length()<(limite1)||(code==KeyEvent.VK_BACK_SPACE)) {
            caja.setEditable(true);
        }else if((caja.getText().length()<(limite1+1))&&(evt.getKeyChar() == '.'&&!caja.getText().contains("."))){
            peCaja9 = caja.getText().length();
            caja.setEditable(true);
	}else if((evt.getKeyChar() >= '0'&&evt.getKeyChar() <= '9')&&(caja.getText().length()<(peCaja9+limite2+1))&&caja.getText().contains(".")){
            caja.setEditable(true);
        }else{
            caja.setEditable(false);
	}
    }//GEN-LAST:event_caja9KeyPressed

    private void caja10KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja10KeyPressed
        int code = evt.getKeyCode();
	int limite = 45;
        JFormattedTextField caja = caja10;
	if ((caja.getText().equals("")?true:!(caja.getText().charAt(caja.getText().length()-1)==' '&&code==KeyEvent.VK_SPACE))&&(caja.getText().length()<limite||code==KeyEvent.VK_BACK_SPACE)) {
		caja.setEditable(true);
	}else{
		caja.setEditable(false);
	}
    }//GEN-LAST:event_caja10KeyPressed

    private void caja11KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja11KeyPressed
        int code = evt.getKeyCode();
	int limite = 45;
        JFormattedTextField caja = caja11;
	if ((caja.getText().equals("")?true:!(caja.getText().charAt(caja.getText().length()-1)==' '&&code==KeyEvent.VK_SPACE))&&(caja.getText().length()<limite||code==KeyEvent.VK_BACK_SPACE)) {
		caja.setEditable(true);
	}else{
		caja.setEditable(false);
	}
    }//GEN-LAST:event_caja11KeyPressed

    private void caja12KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja12KeyPressed
        int code = evt.getKeyCode();
	int limite = 60;
        JFormattedTextField caja = caja12;
	if ((caja.getText().equals("")?true:!(caja.getText().charAt(caja.getText().length()-1)==' '&&code==KeyEvent.VK_SPACE))&&(caja.getText().length()<limite||code==KeyEvent.VK_BACK_SPACE)) {
		caja.setEditable(true);
	}else{
		caja.setEditable(false);
	}
    }//GEN-LAST:event_caja12KeyPressed

    private void caja13KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja13KeyPressed
        int code=evt.getKeyCode();
	int limite=10;
        JFormattedTextField caja = caja13;
	if (((evt.getKeyChar() >= '0'&&evt.getKeyChar() <= '9'))&&caja.getText().length()<limite||(code==KeyEvent.VK_BACK_SPACE)) {
		caja.setEditable(true);
	}else{
		caja.setEditable(false);
	}
    }//GEN-LAST:event_caja13KeyPressed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        caja1.setText("");
        caja2.setText("");
        caja3.setText("");
        caja4.setText("");
        caja5.setText("");
        caja6.setText("");
        caja7.setText("");
        caja8.setText("");
        caja9.setText("");
        caja10.setText("");
        caja11.setText("");
        caja12.setText("");
        caja13.setText("");
        caja14.setText("");
        combo1.setSelectedIndex(-1);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiCountry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiCountry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiCountry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiCountry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guiCountry().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JFormattedTextField caja1;
    private javax.swing.JFormattedTextField caja10;
    private javax.swing.JFormattedTextField caja11;
    private javax.swing.JFormattedTextField caja12;
    private javax.swing.JFormattedTextField caja13;
    private javax.swing.JFormattedTextField caja14;
    private javax.swing.JFormattedTextField caja2;
    private javax.swing.JFormattedTextField caja3;
    private javax.swing.JFormattedTextField caja4;
    private javax.swing.JFormattedTextField caja5;
    private javax.swing.JFormattedTextField caja6;
    private javax.swing.JFormattedTextField caja7;
    private javax.swing.JFormattedTextField caja8;
    private javax.swing.JFormattedTextField caja9;
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
