/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JTable;

/**
 *
 * @author bryan
 */
public class guiCity extends javax.swing.JFrame {

    /**
     * Creates new form guiCity
     */
    public guiCity() {
        initComponents();
        actualizarTabla("SELECT * FROM City;");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        caja1 = new javax.swing.JTextField();
        caja2 = new javax.swing.JTextField();
        caja4 = new javax.swing.JTextField();
        caja5 = new javax.swing.JTextField();
        caja3 = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        setTitle("Formulario ciudad");
        setMinimumSize(new java.awt.Dimension(600, 350));
        getContentPane().setLayout(null);

        jLabel1.setText("ID ciudad");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 70, 14);

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 20, 70, 14);

        jLabel3.setText("Código de país");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 80, 130, 14);

        jLabel4.setText("Distrito");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 80, 70, 14);

        jLabel5.setText("Población");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(290, 20, 80, 14);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.setToolTipText("Borra todos los textos de los campos");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar);
        btnLimpiar.setBounds(440, 100, 100, 23);

        caja1.setToolTipText("Introduce el ID de la ciudad");
        caja1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                caja1KeyPressed(evt);
            }
        });
        getContentPane().add(caja1);
        caja1.setBounds(20, 40, 120, 25);

        caja2.setToolTipText("Introduce el nombre de la ciudad");
        caja2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                caja2KeyPressed(evt);
            }
        });
        getContentPane().add(caja2);
        caja2.setBounds(150, 40, 120, 25);

        caja4.setToolTipText("Introduce el distrito en el que se encuentra");
        caja4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                caja4KeyPressed(evt);
            }
        });
        getContentPane().add(caja4);
        caja4.setBounds(150, 100, 120, 25);

        caja5.setToolTipText("Introduce el tamaño de la población");
        caja5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                caja5KeyPressed(evt);
            }
        });
        getContentPane().add(caja5);
        caja5.setBounds(290, 40, 120, 25);

        try {
            caja3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UUU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        caja3.setToolTipText("Introduce el códigod el país");
        caja3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja3ActionPerformed(evt);
            }
        });
        getContentPane().add(caja3);
        caja3.setBounds(20, 100, 120, 25);

        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 140, 520, 140);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\bryan\\OneDrive\\one drive\\Documentos\\NetBeansProjects\\ProyectoFinalTBD\\archivos\\guiCity.png")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 650, 1050);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        caja1.setText("");
        caja2.setText("");
        caja3.setText("");
        caja4.setText("");
        caja5.setText("");
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    public void actualizarTabla(String sql) {
		ResultSetTableModel modeloDatos =null;
		try {
			modeloDatos = new ResultSetTableModel("com.mysql.cj.jdbc.Driver","jdbc:mysql://localhost:3306/world",sql);
		} catch (ClassNotFoundException e1) {
			e1.printStackTrace();
		} catch (SQLException e1) {
			e1.printStackTrace();
		}
                jScrollPane1.getViewport().remove(jTable1);
		jTable1 = new JTable(modeloDatos);
		jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
		    @Override
		    public void mouseClicked(java.awt.event.MouseEvent evt) {
		    	obtenerRegistroTabla();
		    }
		});
                jScrollPane1.getViewport().add(jTable1);
                
	}
    
    public void obtenerRegistroTabla(){
        caja1.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),0));
        caja2.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),1));
        caja3.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),2));
        caja4.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),3));
        caja5.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),4));
    }
    
    private void caja1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja1KeyPressed
       int code=evt.getKeyCode();
       if (((evt.getKeyChar() >= '0'&&evt.getKeyChar() <= '9'))&&caja1.getText().length()<10||(code==KeyEvent.VK_BACK_SPACE)) {
           caja1.setEditable(true);
       }else{
           caja1.setEditable(false);
       }
    }//GEN-LAST:event_caja1KeyPressed

    private void caja2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja2KeyPressed
        int code = evt.getKeyCode();
        int limite = 35;
        if ((caja2.getText().equals("")?true:!(caja2.getText().charAt(caja2.getText().length()-1)==' '&&code==KeyEvent.VK_SPACE))&&(caja2.getText().length()<limite||code==KeyEvent.VK_BACK_SPACE)) {
            caja2.setEditable(true);
        }else{
            caja2.setEditable(false);
        }
    }//GEN-LAST:event_caja2KeyPressed

    private void caja3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja3ActionPerformed

    private void caja4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja4KeyPressed
        int code = evt.getKeyCode();
        int limite = 20;
        if ((caja4.getText().equals("")?true:!(caja4.getText().charAt(caja4.getText().length()-1)==' '&&code==KeyEvent.VK_SPACE))&&(caja4.getText().length()<limite||code==KeyEvent.VK_BACK_SPACE)) {
                caja4.setEditable(true);
        }else{
                caja4.setEditable(false);
        }
    }//GEN-LAST:event_caja4KeyPressed

    private void caja5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja5KeyPressed
        int code=evt.getKeyCode();
        int limite=10;
        if (((evt.getKeyChar() >= '0'&&evt.getKeyChar() <= '9'))&&caja5.getText().length()<limite||(code==KeyEvent.VK_BACK_SPACE)) {
                caja5.setEditable(true);
        }else{
                caja5.setEditable(false);
        }
    }//GEN-LAST:event_caja5KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiCity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiCity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiCity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiCity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JTextField caja1;
    private javax.swing.JTextField caja2;
    private javax.swing.JFormattedTextField caja3;
    private javax.swing.JTextField caja4;
    private javax.swing.JTextField caja5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
